import Head from 'next/head';
import styles from '../styles/Home.module.scss';
import { ReactComponent as IntroIcon } from '../../public/smarto.svg';
import { Button } from '../components/UI/Button';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <IntroIcon width={400} height={200} />
        <h1 className={styles.title}>Starting template</h1>
        <Button>Click me</Button>
      </main>
    </div>
  );
}
